import React from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { ChevronLeft, ChevronRight, Maximize, X, Grid, Share2 } from 'lucide-react';
import { Page, Catalog, Product } from '../../types';
import { cn } from '../../lib/utils';
import { Serif, Sans, Label } from '../shared/Typography';

export const CatalogReader:React.FC<{catalog:Catalog;pages:Page[];products:Product[]}>=({catalog,pages,products})=>{
 const [i,setI]=React.useState(0),[full,setFull]=React.useState(false),[contents,setContents]=React.useState(false); const page=pages[i];
 const next=()=>setI(x=>Math.min(x+1,pages.length-1)),prev=()=>setI(x=>Math.max(x-1,0));
 if(!page)return <div className="min-h-screen bg-white text-[#0f203a] flex items-center justify-center"><Serif className="text-4xl italic">Catalog Studio</Serif></div>;
 return <div className={cn('relative w-full h-screen bg-[#f7f9fb] text-[#0f203a] flex flex-col overflow-hidden',full&&'fixed inset-0 z-[100] bg-white')}>
  <div className="absolute top-0 left-0 w-full px-8 py-6 flex justify-between items-center z-20 bg-white/80 backdrop-blur-sm border-b border-[#0f203a]/5"><div className="flex items-center gap-4"><img src={catalog.logoUrl||'/venta-logo.svg'} alt="Venta Jewelry" className="h-7 max-w-40 object-contain"/><span className="w-px h-4 bg-[#0f203a]/10"/><span className="text-[10px] uppercase tracking-[0.3em] font-medium opacity-40">{catalog.name}</span></div><div className="flex items-center gap-6"><button onClick={()=>setContents(!contents)}><Grid size={16}/></button><button><Share2 size={16}/></button><button onClick={()=>setFull(!full)}>{full?<X size={16}/>:<Maximize size={16}/>}</button></div></div>
  <main className="flex-1 flex items-center justify-center relative px-8 md:px-16 lg:px-24 pt-20 pb-16"><div className="relative w-full h-full max-w-[1400px] max-h-[800px] bg-white shadow-[0_25px_80px_rgba(15,32,58,.12)] overflow-hidden"><AnimatePresence mode="wait"><motion.div key={page.id} initial={{opacity:0,x:20}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-20}} transition={{duration:.6}} className="w-full h-full"><PageRenderer page={page} products={products.filter(p=>page.content.productIds?.includes(p.id))}/></motion.div></AnimatePresence></div><button onClick={prev} disabled={i===0} className="absolute left-4 top-1/2 -translate-y-1/2 p-4 disabled:opacity-0"><ChevronLeft size={32} strokeWidth={1}/></button><button onClick={next} disabled={i===pages.length-1} className="absolute right-4 top-1/2 -translate-y-1/2 p-4 disabled:opacity-0"><ChevronRight size={32} strokeWidth={1}/></button></main>
  <div className="absolute bottom-0 left-0 w-full p-6 flex justify-center"><span className="text-[10px] uppercase tracking-[0.3em] opacity-40">{String(i+1).padStart(2,'0')} / {String(pages.length).padStart(2,'0')}</span></div>
  {contents&&<div className="absolute top-20 right-8 z-30 w-64 bg-white/95 backdrop-blur p-4 shadow-xl border border-[#0f203a]/10"><Label>Contents</Label>{pages.map((p,n)=><button key={p.id} onClick={()=>{setI(n);setContents(false)}} className="block w-full text-left py-2 text-xs border-b border-[#0f203a]/10">{String(n+1).padStart(2,'0')} · {p.title}</button>)}</div>}
 </div>;
};

const PageRenderer:React.FC<{page:Page;products:Product[]}>=({page,products})=>{const img=page.content.images?.[0]; switch(page.layoutId){
 case 'COVER':return <div className="relative w-full h-full bg-white text-[#0f203a] flex items-center justify-center text-center overflow-hidden">{img&&<img src={img} className="absolute inset-0 w-full h-full object-cover opacity-15"/>}<div className="relative z-10 px-10"><Label>{page.content.subheadline||'SPRING / SUMMER 2027'}</Label><h1 className="font-serif italic text-7xl md:text-9xl tracking-tighter">{page.content.headline||'AURA'}</h1><Sans className="text-[#0f203a]/60 text-xs tracking-[.25em] uppercase">{page.content.body}</Sans></div></div>;
 case 'LAYOUT_A_FULL_BLEED':return <div className="relative w-full h-full">{img&&<img src={img} className="w-full h-full object-cover"/>}<div className="absolute inset-x-12 bottom-12 text-white drop-shadow-lg"><Serif className="text-5xl">{page.content.headline}</Serif><Sans className="text-white/80 text-sm mt-3 max-w-md">{page.content.body}</Sans></div></div>;
 case 'LAYOUT_H_TYPOGRAPHIC':return <div className="w-full h-full flex flex-col justify-center p-20 bg-[#f7f5f0]"><Label>{catalogLabel()}</Label><Serif className="text-6xl italic max-w-3xl">{page.content.headline}</Serif><Sans className="max-w-xl mt-8 text-sm opacity-60 leading-relaxed">{page.content.body}</Sans></div>;
 case 'LAYOUT_B_HERO_PRODUCT':return <div className="w-full h-full grid grid-cols-2">{img&&<img src={img} className="w-full h-full object-cover"/>}<div className="p-16 flex flex-col justify-end"><Label>Featured Piece</Label><Serif className="text-5xl italic">{page.content.headline}</Serif>{products[0]&&<ProductCard product={products[0]}/>}</div></div>;
 case 'LAYOUT_C_PRODUCT_GRID':return <div className="w-full h-full p-14 bg-white"><Serif className="text-3xl italic mb-10">{page.content.headline}</Serif><div className="grid grid-cols-4 gap-6">{products.map(p=><ProductCard key={p.id} product={p}/>)}</div></div>;
 case 'LAYOUT_D_ASYMMETRIC':return <div className="w-full h-full grid grid-cols-12 gap-8 p-16"><div className="col-span-7">{img&&<img src={img} className="w-full h-full object-cover"/>}</div><div className="col-span-5 flex flex-col justify-end"><Serif className="text-5xl italic">{page.content.headline}</Serif><Sans className="text-sm opacity-60 mt-4">{page.content.body}</Sans><div className="grid grid-cols-2 gap-5 mt-8">{products.slice(0,2).map(p=><ProductCard key={p.id} product={p}/>)}</div></div></div>;
 case 'LAYOUT_F_TWO_UP':return <div className="w-full h-full grid grid-cols-2">{products.slice(0,2).map(p=><div key={p.id} className="relative"><ProductImage product={p}/><div className="absolute bottom-8 left-8 text-white drop-shadow-lg"><Label className="text-white">{p.sku}</Label><Serif className="text-2xl italic">{p.name}</Serif></div></div>)}</div>;
 case 'LAYOUT_K_LOOK_PAGE':return <div className="relative w-full h-full overflow-hidden">{img&&<img src={img} className="w-full h-full object-cover"/>}<div className="absolute top-12 left-12 text-white drop-shadow-lg"><Serif className="text-5xl italic">{page.content.headline}</Serif><Sans className="text-white/80 text-xs">{page.content.body}</Sans></div></div>;
 case 'LAYOUT_L_COLLECTION_INDEX':return <div className="w-full h-full p-24 flex flex-col justify-center bg-[#f7f7f5]"><Label>Collection Index</Label><Serif className="text-7xl italic">{page.title}</Serif><div className="mt-10 space-y-3">{products.map((p,n)=><div key={p.id} className="flex justify-between border-b border-neutral-300 pb-2 text-sm"><span>{String(n+1).padStart(2,'0')} · {p.name}</span><span className="opacity-40">{p.sku}</span></div>)}</div></div>;
 default:return <div className="w-full h-full flex items-center justify-center"><Serif className="text-4xl italic">{page.content.headline||page.title}</Serif></div>}}
const catalogLabel=()=> 'ETERNAL FORM';
const ProductImage:React.FC<{product:Product}>=({product})=><div className="w-full h-full bg-neutral-100">{product.images[0]&&<img src={product.images[0]} className="w-full h-full object-cover"/>}</div>;
const ProductCard:React.FC<{product:Product}>=({product})=><div className="space-y-2"><div className="aspect-[3/4] overflow-hidden bg-neutral-50"><ProductImage product={product}/></div><Label>{product.name}</Label><div className="text-[9px] opacity-40">{product.sku}</div></div>;
