import React from 'react';
import { ArrowRight, BookOpen, Loader2, LogIn, LogOut, User, Users } from 'lucide-react';
import { Catalog, Page, Product } from './types';
import { mockCatalog, mockPages, mockProducts } from './mockData';
import { CatalogReader } from './components/reader/CatalogReader';
import { CatalogStudio } from './components/studio/CatalogStudio';
import { fetchShopifyProducts, getShopifyStatus, loadCatalogState, saveCatalogState } from './lib/shopify';

const LOGO_SRC='/venta-logo.svg';
const BRAND='#0f203a';
type User={username:string;role:'admin'|'user'};

async function getUser():Promise<User|null>{try{const r=await fetch('/api/user-auth',{credentials:'include'});const d=await r.json();return d.authenticated?d.user:null}catch{return null}}
async function login(username:string,password:string){const r=await fetch('/api/user-auth',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Giriş başarısız.');return d.user as User}
async function logout(){await fetch('/api/user-auth',{method:'DELETE',credentials:'include'});location.href='/admin'}
const Logo=({className=''}:{className?:string})=><img src={LOGO_SRC} alt="Venta Jewelry" className={`object-contain ${className}`}/>;

function LoginPage({onLogin}:{onLogin:(u:User)=>void}){const [username,setUsername]=React.useState('');const [password,setPassword]=React.useState('');const [error,setError]=React.useState('');const [busy,setBusy]=React.useState(false);const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{onLogin(await login(username,password))}catch(err:any){setError(err.message)}finally{setBusy(false)}};return <div className="min-h-screen bg-white text-[#0f203a] flex items-center justify-center px-6"><div className="w-full max-w-md"><div className="text-center mb-10"><Logo className="w-full max-w-sm mx-auto mb-8"/><div className="w-10 h-px bg-[#0f203a]/20 mx-auto mb-5"/><p className="text-[10px] uppercase tracking-[.35em] opacity-50">Catalog Studio · Internal Access</p></div><form onSubmit={submit} className="bg-white border border-[#0f203a]/10 shadow-[0_20px_60px_rgba(15,32,58,.08)] p-8 space-y-5"><div><label className="text-[10px] uppercase tracking-[.2em] opacity-50 block mb-2">Kullanıcı Adı</label><input autoFocus value={username} onChange={e=>setUsername(e.target.value)} className="w-full h-12 border border-[#0f203a]/15 px-4 outline-none focus:border-[#0f203a] text-sm"/></div><div><label className="text-[10px] uppercase tracking-[.2em] opacity-50 block mb-2">Şifre</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)} className="w-full h-12 border border-[#0f203a]/15 px-4 outline-none focus:border-[#0f203a] text-sm"/></div>{error&&<p className="text-xs text-red-600">{error}</p>}<button disabled={busy||!username||!password} className="w-full h-12 bg-[#0f203a] text-white text-[10px] uppercase tracking-[.25em] font-semibold flex items-center justify-center gap-2 disabled:opacity-40">{busy?<Loader2 size={15} className="animate-spin"/>:<LogIn size={15}/>} Giriş Yap</button></form><p className="text-center text-[10px] opacity-40 mt-6">Yalnızca yetkili Venta Jewelry kullanıcıları</p></div></div>}

function AdminPanel({user,onOpenStudio,onPreview}:{user:User;onOpenStudio:()=>void;onPreview:()=>void}){return <div className="min-h-screen bg-[#f7f9fb] text-[#0f203a]"><header className="h-20 bg-white border-b border-[#0f203a]/10 px-8 flex items-center justify-between"><div className="flex items-center gap-6"><Logo className="w-40 h-auto"/><span className="h-5 w-px bg-[#0f203a]/10"/><span className="text-[10px] uppercase tracking-[.25em] opacity-50">Catalog Studio / Admin</span></div><div className="flex items-center gap-5"><div className="text-right"><p className="text-xs font-medium">{user.username}</p><p className="text-[9px] uppercase tracking-[.18em] opacity-40">{user.role==='admin'?'Yönetici':'Kullanıcı'}</p></div><button onClick={logout} className="p-2 hover:bg-[#0f203a]/5" title="Çıkış"><LogOut size={16}/></button></div></header><main className="max-w-7xl mx-auto px-8 py-12"><div className="mb-12"><p className="text-[10px] uppercase tracking-[.3em] opacity-40 mb-3">Venta Jewelry</p><h1 className="font-serif text-5xl tracking-tight">Kontrol Paneli</h1><p className="mt-3 text-sm opacity-50">Katalog operasyonları ve yayın yönetimi.</p></div><div className="grid md:grid-cols-3 gap-5"><button onClick={onOpenStudio} className="text-left bg-white border border-[#0f203a]/10 p-7 hover:border-[#0f203a]/30 hover:shadow-lg transition"><BookOpen size={22} strokeWidth={1.5}/><h2 className="mt-8 font-serif text-2xl">Catalog Studio</h2><p className="mt-2 text-xs opacity-50">Sayfaları, ürünleri ve editorial yerleşimleri düzenle.</p><span className="mt-6 inline-flex items-center gap-2 text-[10px] uppercase tracking-[.2em] font-semibold">Stüdyoyu Aç <ArrowRight size={13}/></span></button><button onClick={onPreview} className="text-left bg-white border border-[#0f203a]/10 p-7 hover:border-[#0f203a]/30 hover:shadow-lg transition"><BookOpen size={22} strokeWidth={1.5}/><h2 className="mt-8 font-serif text-2xl">Kataloğu Görüntüle</h2><p className="mt-2 text-xs opacity-50">Müşterinin göreceği katalog deneyimini aç.</p><span className="mt-6 inline-flex items-center gap-2 text-[10px] uppercase tracking-[.2em] font-semibold">Önizle <ArrowRight size={13}/></span></button>{user.role==='admin'?<button className="text-left bg-white border border-[#0f203a]/10 p-7 hover:border-[#0f203a]/30 hover:shadow-lg transition"><Users size={22} strokeWidth={1.5}/><h2 className="mt-8 font-serif text-2xl">Kullanıcılar</h2><p className="mt-2 text-xs opacity-50">Yönetici ve kullanıcı erişimlerinin kontrol merkezi.</p><span className="mt-6 inline-flex items-center gap-2 text-[10px] uppercase tracking-[.2em] font-semibold">Yönet <ArrowRight size={13}/></span></button>:<div className="text-left bg-[#0f203a] text-white p-7"><User size={22} strokeWidth={1.5}/><h2 className="mt-8 font-serif text-2xl">Kullanıcı Alanı</h2><p className="mt-2 text-xs text-white/60">Yetkinize göre tanımlanmış Catalog Studio erişimi.</p></div>}</div></main></div>}

export default function App(){const path=window.location.pathname.replace(/\/$/,'')||'/';const [user,setUser]=React.useState<User|null>(null);const [authLoading,setAuthLoading]=React.useState(path==='/admin');const [view,setView]=React.useState<'reader'|'studio'>('reader');const [catalog,setCatalog]=React.useState<Catalog>({...mockCatalog,logoUrl:LOGO_SRC,theme:{...mockCatalog.theme,primaryColor:BRAND}});const [pages,setPages]=React.useState<Page[]>(mockPages);const [products,setProducts]=React.useState<Product[]>(mockProducts);const [connected,setConnected]=React.useState(false);const [loading,setLoading]=React.useState(path==='/admin');const [error,setError]=React.useState('');
React.useEffect(()=>{if(path==='/admin'){getUser().then(setUser).finally(()=>setAuthLoading(false));}},[path]);
const hydrate=React.useCallback(async()=>{setLoading(true);try{const s=await getShopifyStatus();setConnected(s.connected);if(s.connected){const [pd,cs]=await Promise.all([fetchShopifyProducts(),loadCatalogState()]);setProducts(pd.products);if(cs){setCatalog({...cs.catalog,logoUrl:LOGO_SRC});if(cs.pages?.length)setPages(cs.pages)}}}catch(e:any){setError(e.message||'Veriler yüklenemedi.')}finally{setLoading(false)}},[]);
React.useEffect(()=>{if(path==='/admin'&&user)hydrate()},[path,user,hydrate]);
React.useEffect(()=>{if(!user||!connected||loading)return;const t=window.setTimeout(()=>saveCatalogState({...catalog,updatedAt:new Date().toISOString()},pages).catch(e=>setError(e.message||'Katalog kaydedilemedi.')),900);return()=>clearTimeout(t)},[catalog,pages,user,connected,loading]);
const updatePage=(p:Page)=>setPages(x=>x.map(y=>y.id===p.id?p:y));const addPage=()=>setPages(x=>[...x,{id:crypto.randomUUID(),catalogId:catalog.id,order:x.length,layoutId:'LAYOUT_A_FULL_BLEED',title:`Page ${x.length+1}`,content:{}}]);const delPage=(id:string)=>setPages(x=>x.filter(p=>p.id!==id).map((p,i)=>({...p,order:i})));
if(path==='/admin'&&authLoading)return <div className="min-h-screen bg-white flex items-center justify-center text-[#0f203a]"><Loader2 className="animate-spin"/></div>;
if(path==='/admin'&&!user)return <LoginPage onLogin={u=>setUser(u)}/>;
if(path==='/admin'&&user&&view==='studio')return <CatalogStudio catalog={catalog} pages={[...pages].sort((a,b)=>a.order-b.order)} products={products} onUpdatePage={updatePage} onAddPage={addPage} onDeletePage={delPage} onExit={()=>setView('reader')} canPublish={user.role==='admin'} onPreview={()=>setView('reader')}/>;
if(path==='/admin'&&user)return <AdminPanel user={user} onOpenStudio={()=>setView('studio')} onPreview={()=>window.location.href='/'}/>;
return <CatalogReader catalog={catalog} pages={[...pages].sort((a,b)=>a.order-b.order)} products={products}/>;
}
