import React from 'react';
import { motion } from 'motion/react';
import { Plus, Trash2, Layout as LayoutIcon, Image as ImageIcon, Type, Package, Eye, ArrowLeft, GripVertical } from 'lucide-react';
import { Page, Catalog, Product, LayoutId } from '../../types';
import { cn } from '../../lib/utils';
import { Label, Serif, Sans } from '../shared/Typography';

interface CatalogStudioProps { catalog: Catalog; pages: Page[]; products: Product[]; onUpdatePage: (page: Page) => void; onAddPage: () => void; onDeletePage: (id: string) => void; onExit: () => void; }

export const CatalogStudio: React.FC<CatalogStudioProps> = ({catalog,pages,products,onUpdatePage,onAddPage,onDeletePage,onExit}) => {
  const [selectedPageId,setSelectedPageId]=React.useState<string|null>(pages[0]?.id||null); const selectedPage=pages.find(p=>p.id===selectedPageId);
  return <div className="flex h-screen bg-[#fafafa] text-neutral-900 font-sans">
    <aside className="w-72 bg-white border-r border-neutral-100 flex flex-col h-full"><div className="p-6 border-b border-neutral-100 flex justify-between items-center"><button onClick={onExit} className="p-2 hover:bg-neutral-50 rounded-full"><ArrowLeft size={18}/></button><Label className="mb-0">Studio</Label><button onClick={onAddPage} className="p-2 hover:bg-neutral-50 rounded-full"><Plus size={18}/></button></div><div className="flex-1 overflow-y-auto p-4 space-y-3">{pages.map((page,index)=><div key={page.id} onClick={()=>setSelectedPageId(page.id)} className={cn('group relative p-3 rounded-lg border transition-all cursor-pointer',selectedPageId===page.id?'bg-white border-black shadow-sm':'bg-transparent border-transparent hover:border-neutral-200')}><div className="flex items-center gap-3"><span className="text-[10px] opacity-40 font-medium">{String(index+1).padStart(2,'0')}</span><span className="text-xs font-medium truncate">{page.title||'Untitled Page'}</span></div><div className="mt-2 aspect-[4/3] bg-neutral-100 rounded overflow-hidden"><div className="w-full h-full flex items-center justify-center opacity-10"><LayoutIcon size={24}/></div></div><button onClick={e=>{e.stopPropagation();onDeletePage(page.id)}} className="absolute top-2 right-2 p-1.5 bg-white shadow-sm border border-neutral-100 rounded-md opacity-0 group-hover:opacity-100 hover:text-red-500"><Trash2 size={12}/></button></div>)}</div></aside>
    <main className="flex-1 overflow-hidden flex flex-col"><header className="h-16 bg-white border-b border-neutral-100 px-8 flex justify-between items-center"><div className="flex items-center gap-4"><h1 className="text-sm font-medium">{catalog.name}</h1><span className="w-px h-4 bg-neutral-200"/><span className="text-xs opacity-40">Auto-saved</span></div><div className="flex items-center gap-4"><button className="px-4 py-2 text-xs font-medium border border-neutral-200 rounded-md hover:bg-neutral-50">Preview</button><button className="px-4 py-2 text-xs font-medium bg-black text-white rounded-md">Publish</button></div></header><div className="flex-1 overflow-auto bg-neutral-100 p-12 flex justify-center items-center">{selectedPage?<div className="w-full max-w-[1000px] aspect-[1.6] bg-white shadow-2xl origin-center overflow-hidden"><PageCanvas page={selectedPage} products={products}/></div>:<div className="text-center opacity-30"><LayoutIcon size={48} className="mx-auto mb-4"/><Sans>Select a page to edit</Sans></div>}</div></main>
    <aside className="w-80 bg-white border-l border-neutral-100 h-full flex flex-col">{selectedPage?<PageProperties page={selectedPage} products={products} onUpdate={updates=>onUpdatePage({...selectedPage,...updates})}/>:<div className="p-8 text-center opacity-20"><Sans className="text-xs">Select a page to view properties</Sans></div>}</aside>
  </div>;
};

const PageCanvas:React.FC<{page:Page;products:Product[]}>=({page})=><div className="w-full h-full border-4 border-neutral-50 flex items-center justify-center p-10"><div className="text-center space-y-4 opacity-40"><Label>Preview: {page.layoutId}</Label><Serif className="text-2xl">{page.content.headline||'No Headline'}</Serif></div></div>;

const PageProperties:React.FC<{page:Page;products:Product[];onUpdate:(updates:Partial<Page>)=>void}>=({page,products,onUpdate})=><div className="flex flex-col h-full"><div className="p-6 border-b border-neutral-100"><Label className="mb-4">Page Properties</Label><input type="text" value={page.title} onChange={e=>onUpdate({title:e.target.value})} className="w-full px-3 py-2 text-sm border border-neutral-200 rounded-md focus:outline-none focus:border-black" placeholder="Page Title"/></div><div className="flex-1 overflow-y-auto p-6 space-y-8"><section className="space-y-4"><Label>Layout</Label><div className="grid grid-cols-3 gap-2">{(['COVER','LAYOUT_A_FULL_BLEED','LAYOUT_H_TYPOGRAPHIC','LAYOUT_B_HERO_PRODUCT','LAYOUT_C_PRODUCT_GRID','LAYOUT_D_ASYMMETRIC','LAYOUT_F_TWO_UP','LAYOUT_K_LOOK_PAGE','LAYOUT_L_COLLECTION_INDEX'] as LayoutId[]).map(id=><button key={id} onClick={()=>onUpdate({layoutId:id})} className={cn('aspect-square flex flex-col items-center justify-center border rounded-md transition-all',page.layoutId===id?'border-black bg-neutral-50':'border-neutral-100 hover:border-neutral-300')}><LayoutIcon size={16} strokeWidth={1.5} className={cn(page.layoutId===id?'opacity-100':'opacity-40')}/><span className="text-[8px] mt-2 font-medium opacity-60 truncate w-full px-1 text-center">{id.replace('LAYOUT_','').replace('_',' ')}</span></button>)}</div></section><section className="space-y-4"><Label>Copy</Label><div className="space-y-3"><div><span className="text-[10px] opacity-40 block mb-1">Headline</span><input type="text" value={page.content.headline||''} onChange={e=>onUpdate({content:{...page.content,headline:e.target.value}})} className="w-full px-3 py-2 text-xs border border-neutral-200 rounded-md"/></div><div><span className="text-[10px] opacity-40 block mb-1">Body</span><textarea value={page.content.body||''} onChange={e=>onUpdate({content:{...page.content,body:e.target.value}})} className="w-full px-3 py-2 text-xs border border-neutral-200 rounded-md h-24 resize-none"/></div></div></section><section className="space-y-4"><Label>Products</Label><div className="space-y-2">{products.map(product=><label key={product.id} className="flex items-center gap-3 p-2 border border-neutral-100 rounded-md cursor-pointer hover:bg-neutral-50"><input type="checkbox" checked={!!page.content.productIds?.includes(product.id)} onChange={e=>{const current=page.content.productIds||[];const next=e.target.checked?[...current,product.id]:current.filter(id=>id!==product.id);onUpdate({content:{...page.content,productIds:next}})}} className="rounded border-neutral-300"/><div className="flex-1"><p className="text-[10px] font-medium">{product.name}</p><p className="text-[8px] opacity-40">{product.sku}</p></div></label>)}</div></section></div></div>;
