import React from 'react';
import { Plus, Trash2, Layout as LayoutIcon, Eye, ArrowLeft, Search, Check, ChevronDown, Package, Layers3, UploadCloud } from 'lucide-react';
import { Page, Catalog, Product, LayoutId } from '../../types';
import { cn } from '../../lib/utils';
import { Label, Serif, Sans } from '../shared/Typography';

interface CatalogStudioProps { catalog: Catalog; pages: Page[]; products: Product[]; onUpdatePage:(page:Page)=>void; onUpdateCatalog:(updates:Partial<Catalog>)=>void; onAddPage:()=>void; onDeletePage:(id:string)=>void; onExit:()=>void; canPublish?:boolean; onPublish?:()=>Promise<void>|void; onPreview?:()=>void; }

export const CatalogStudio:React.FC<CatalogStudioProps>=({catalog,pages,products,onUpdatePage,onUpdateCatalog,onAddPage,onDeletePage,onExit,canPublish=true,onPublish,onPreview})=>{
 const [selectedPageId,setSelectedPageId]=React.useState<string|null>(pages[0]?.id||null); const [publishing,setPublishing]=React.useState(false);
 const selectedPage=pages.find(p=>p.id===selectedPageId);
 const publish=async()=>{if(!onPublish||publishing)return;setPublishing(true);try{await onPublish()}finally{setPublishing(false)}};
 return <div className="flex h-screen bg-[#f7f9fb] text-[#0f203a] font-sans">
  <aside className="w-72 bg-white border-r border-[#0f203a]/10 flex flex-col h-full">
   <div className="p-6 border-b border-[#0f203a]/10 flex justify-between items-center"><button onClick={onExit} className="p-2 hover:bg-[#0f203a]/5"><ArrowLeft size={18}/></button><Label className="mb-0">Studio</Label>{canPublish&&<button onClick={onAddPage} className="p-2 hover:bg-[#0f203a]/5"><Plus size={18}/></button>}</div>
   <div className="flex-1 overflow-y-auto p-4 space-y-3">{pages.map((page,index)=><div key={page.id} onClick={()=>setSelectedPageId(page.id)} className={cn('group relative p-3 border transition-all cursor-pointer',selectedPageId===page.id?'bg-white border-[#0f203a] shadow-sm':'bg-transparent border-transparent hover:border-[#0f203a]/15')}><div className="flex items-center gap-3"><span className="text-[10px] opacity-40 font-medium">{String(index+1).padStart(2,'0')}</span><span className="text-xs font-medium truncate">{page.title||'Untitled Page'}</span></div><div className="mt-2 aspect-[4/3] bg-[#f1f4f7] flex items-center justify-center"><LayoutIcon size={24} className="opacity-10"/>{canPublish&&<button onClick={e=>{e.stopPropagation();onDeletePage(page.id)}} className="absolute top-2 right-2 p-1.5 bg-white shadow-sm border border-[#0f203a]/10 opacity-0 group-hover:opacity-100 hover:text-red-600"><Trash2 size={12}/></button>}</div></div>)}</div>
  </aside>
  <main className="flex-1 overflow-hidden flex flex-col">
   <header className="h-16 bg-white border-b border-[#0f203a]/10 px-8 flex justify-between items-center"><div className="flex items-center gap-4"><h1 className="text-sm font-medium">{catalog.name}</h1><span className="w-px h-4 bg-[#0f203a]/15"/><span className="text-xs opacity-40">{catalog.status==='published'?'Yayında':'Taslak'}</span></div><div className="flex items-center gap-3"><button onClick={onPreview} className="px-4 py-2 text-xs font-medium border border-[#0f203a]/15 hover:bg-[#0f203a]/5 flex items-center gap-2"><Eye size={14}/> Önizle</button>{canPublish?<button onClick={publish} disabled={publishing} className="px-5 py-2 text-xs font-medium bg-[#0f203a] text-white disabled:opacity-50">{publishing?'Yayınlanıyor…':'Yayınla'}</button>:<span className="px-4 py-2 text-[10px] uppercase tracking-[.15em] opacity-40 border border-[#0f203a]/10">Salt kullanıcı</span>}</div></header>
   <div className="flex-1 overflow-auto bg-[#eef2f6] p-12 flex justify-center items-center">{selectedPage?<div className="w-full max-w-[1000px] aspect-[1.6] bg-white shadow-2xl overflow-hidden"><PageCanvas page={selectedPage} products={products}/></div>:<div className="text-center opacity-30"><LayoutIcon size={48} className="mx-auto mb-4"/><Sans>Bir sayfa seç</Sans></div>}</div>
  </main>
  <aside className="w-[390px] bg-white border-l border-[#0f203a]/10 h-full flex flex-col">{selectedPage?<PageProperties catalog={catalog} page={selectedPage} products={products} onUpdate={updates=>onUpdatePage({...selectedPage,...updates})} onUpdateCatalog={onUpdateCatalog} readOnly={!canPublish}/>:<div className="p-8 text-center opacity-20"><Sans className="text-xs">Bir sayfa seç</Sans></div>}</aside>
 </div>
};

const PageCanvas:React.FC<{page:Page;products:Product[]}>=({page})=><div className="w-full h-full border-4 border-[#f1f4f7] flex items-center justify-center p-10"><div className="text-center space-y-4 opacity-40"><Label>Preview: {page.layoutId}</Label><Serif className="text-2xl">{page.content.headline||'No Headline'}</Serif><p className="text-[10px]">{page.content.productIds?.length||0} ürün seçildi</p></div></div>;

const PageProperties:React.FC<{catalog:Catalog;page:Page;products:Product[];onUpdate:(updates:Partial<Page>)=>void;onUpdateCatalog:(updates:Partial<Catalog>)=>void;readOnly:boolean}>=({catalog,page,products,onUpdate,onUpdateCatalog,readOnly})=>{
 const [search,setSearch]=React.useState(''); const [mode,setMode]=React.useState<'all'|'name'|'sku'|'collection'>('all'); const [collection,setCollection]=React.useState('');
 const selectedIds=page.content.productIds||[];
 const collections=React.useMemo(()=>Array.from(new Set(products.flatMap(p=>p.collectionNames||[]).filter(Boolean))).sort((a,b)=>a.localeCompare(b,'tr')),[products]);
 const filtered=React.useMemo(()=>{const q=search.trim().toLocaleLowerCase('tr-TR');return products.filter(p=>{if(mode==='collection'&&collection&&!(p.collectionNames||[]).includes(collection))return false;if(!q)return true;if(mode==='name')return p.name.toLocaleLowerCase('tr-TR').includes(q);if(mode==='sku')return p.sku.toLocaleLowerCase('tr-TR').includes(q);if(mode==='collection')return (p.collectionNames||[]).some(c=>c.toLocaleLowerCase('tr-TR').includes(q));return [p.name,p.sku,p.category,...(p.collectionNames||[]),...(p.tags||[])].join(' ').toLocaleLowerCase('tr-TR').includes(q);});},[products,search,mode,collection]);
 const updateSelected=(id:string,checked:boolean)=>{const next=checked?Array.from(new Set([...selectedIds,id])):selectedIds.filter(x=>x!==id);onUpdate({content:{...page.content,productIds:next}})};
 const selectVisible=()=>onUpdate({content:{...page.content,productIds:Array.from(new Set([...selectedIds,...filtered.map(p=>p.id)]))}});
 const clearVisible=()=>{const visible=new Set(filtered.map(p=>p.id));onUpdate({content:{...page.content,productIds:selectedIds.filter(id=>!visible.has(id))}})};
 return <div className="flex flex-col h-full">
  <div className="p-6 border-b border-[#0f203a]/10"><Label className="mb-4">Page Properties</Label><input disabled={readOnly} type="text" value={page.title} onChange={e=>onUpdate({title:e.target.value})} className="w-full px-3 py-2 text-sm border border-[#0f203a]/15 rounded-md disabled:bg-[#f5f7f9]" placeholder="Page Title"/></div>
  <div className="flex-1 overflow-y-auto p-6 space-y-8">
   <section className="space-y-4"><Label>Branding</Label><div className="p-4 bg-[#f7f9fb] border border-[#0f203a]/10 rounded-lg space-y-3"><div><span className="text-[10px] opacity-40 block mb-1">Logo URL</span><input disabled={readOnly} type="url" value={catalog.logoUrl||''} onChange={e=>onUpdateCatalog({logoUrl:e.target.value||undefined})} className="w-full px-3 py-2 text-xs bg-white border border-[#0f203a]/15 rounded-md" placeholder="https://…/logo.png"/></div><div className="flex items-center gap-3"><div className="w-20 h-12 bg-white border border-[#0f203a]/10 rounded flex items-center justify-center overflow-hidden">{catalog.logoUrl?<img src={catalog.logoUrl} alt="Logo" className="max-w-full max-h-full object-contain"/>:<UploadCloud size={15} className="opacity-30"/>}</div><p className="text-[9px] opacity-40">Logo, katalog ayarlarıyla birlikte kaydedilir.</p></div></div></section>
   <section className="space-y-4"><Label>Layout</Label><div className="grid grid-cols-3 gap-2">{(['COVER','LAYOUT_A_FULL_BLEED','LAYOUT_H_TYPOGRAPHIC','LAYOUT_B_HERO_PRODUCT','LAYOUT_C_PRODUCT_GRID','LAYOUT_D_ASYMMETRIC','LAYOUT_F_TWO_UP','LAYOUT_K_LOOK_PAGE','LAYOUT_L_COLLECTION_INDEX'] as LayoutId[]).map(id=><button disabled={readOnly} key={id} onClick={()=>onUpdate({layoutId:id})} className={cn('aspect-square flex flex-col items-center justify-center border rounded-md transition-all disabled:opacity-50',page.layoutId===id?'border-[#0f203a] bg-[#f5f7f9]':'border-[#0f203a]/10 hover:border-[#0f203a]/30')}><LayoutIcon size={16} strokeWidth={1.5}/><span className="text-[8px] mt-2 font-medium opacity-60 truncate w-full px-1 text-center">{id.replace('LAYOUT_','').replace(/_/g,' ')}</span></button>)}</div></section>
   <section className="space-y-4"><Label>Copy</Label><div className="space-y-3"><div><span className="text-[10px] opacity-40 block mb-1">Headline</span><input disabled={readOnly} type="text" value={page.content.headline||''} onChange={e=>onUpdate({content:{...page.content,headline:e.target.value}})} className="w-full px-3 py-2 text-xs border border-[#0f203a]/15 rounded-md disabled:bg-[#f5f7f9]"/></div><div><span className="text-[10px] opacity-40 block mb-1">Body</span><textarea disabled={readOnly} value={page.content.body||''} onChange={e=>onUpdate({content:{...page.content,body:e.target.value}})} className="w-full px-3 py-2 text-xs border border-[#0f203a]/15 rounded-md h-24 resize-none disabled:bg-[#f5f7f9]"/></div></div></section>
   <section className="space-y-4">
    <div className="flex items-center justify-between"><div className="flex items-center gap-2"><Layers3 size={15}/><Label className="mb-0">Ürün Seçimi</Label></div><span className="text-[10px] font-medium px-2 py-1 bg-[#0f203a] text-white rounded-full">{selectedIds.length} seçili</span></div>
    <div className="p-3 bg-[#f7f9fb] border border-[#0f203a]/10 rounded-lg space-y-3">
     <div className="relative"><Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 opacity-40"/><input disabled={readOnly} value={search} onChange={e=>setSearch(e.target.value)} className="w-full h-10 pl-9 pr-3 text-xs bg-white border border-[#0f203a]/15 rounded-md outline-none focus:border-[#0f203a]" placeholder={mode==='name'?'Ürün adına göre ara…':mode==='sku'?'SKU numarasına göre ara…':mode==='collection'?'Koleksiyon adına göre ara…':'Ürün, SKU, koleksiyon veya etiket ara…'}/></div>
     <div className="grid grid-cols-2 gap-2"><div className="relative"><select disabled={readOnly} value={mode} onChange={e=>{setMode(e.target.value as typeof mode);setSearch('');setCollection('')}} className="appearance-none w-full h-9 px-3 pr-8 text-[10px] font-medium uppercase tracking-[.08em] bg-white border border-[#0f203a]/15 rounded-md outline-none"><option value="all">Tüm alanlarda</option><option value="name">Ürün adına göre</option><option value="sku">SKU numarasına göre</option><option value="collection">Koleksiyona göre</option></select><ChevronDown size={13} className="absolute right-3 top-1/2 -translate-y-1/2 pointer-events-none opacity-50"/></div><div className="relative"><select disabled={readOnly||mode!=='collection'} value={collection} onChange={e=>setCollection(e.target.value)} className="appearance-none w-full h-9 px-3 pr-8 text-[10px] bg-white border border-[#0f203a]/15 rounded-md outline-none disabled:opacity-40"><option value="">Tüm koleksiyonlar</option>{collections.map(c=><option key={c} value={c}>{c}</option>)}</select><ChevronDown size={13} className="absolute right-3 top-1/2 -translate-y-1/2 pointer-events-none opacity-50"/></div></div>
     <div className="flex items-center justify-between pt-1"><span className="text-[9px] opacity-40">{filtered.length} ürün bulundu / {products.length} toplam</span>{!readOnly&&<div className="flex gap-2"><button onClick={selectVisible} disabled={!filtered.length} className="text-[9px] font-semibold uppercase tracking-[.08em] hover:underline">Görünenleri seç</button><button onClick={clearVisible} disabled={!filtered.length} className="text-[9px] opacity-50 hover:opacity-100">Seçimi kaldır</button></div>}</div>
    </div>
    <div className="space-y-2 max-h-[360px] overflow-y-auto pr-1">{filtered.length?filtered.map(product=>{const checked=selectedIds.includes(product.id);return <label key={product.id} className={cn('flex items-center gap-3 p-2.5 border rounded-lg cursor-pointer transition',checked?'border-[#0f203a] bg-[#f7f9fb]':'border-[#0f203a]/10 hover:border-[#0f203a]/25')}><input disabled={readOnly} type="checkbox" checked={checked} onChange={e=>updateSelected(product.id,e.target.checked)} className="sr-only"/><span className={cn('w-5 h-5 shrink-0 rounded border flex items-center justify-center',checked?'bg-[#0f203a] border-[#0f203a] text-white':'border-[#0f203a]/20 bg-white')}>{checked&&<Check size={13}/>}</span>{product.images?.[0]?<img src={product.images[0]} alt="" className="w-11 h-11 rounded-md object-cover bg-[#f1f4f7]"/>:<span className="w-11 h-11 rounded-md bg-[#f1f4f7] flex items-center justify-center"><Package size={16} className="opacity-30"/></span>}<div className="min-w-0 flex-1"><p className="text-[10px] font-semibold truncate">{product.name}</p><p className="text-[8px] opacity-45 truncate">SKU: {product.sku||'—'}{product.collectionNames?.length?` · ${product.collectionNames.join(', ')}`:''}</p></div></label>}) : <div className="py-10 text-center border border-dashed border-[#0f203a]/10 rounded-lg"><Search size={20} className="mx-auto mb-2 opacity-20"/><p className="text-[10px] opacity-40">Aramanızla eşleşen ürün yok.</p></div>}</div>
   </section>
  </div>
 </div>;
};
